version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    command: gunicorn wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/.staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.docker
    depends_on:
      - db
      - cache
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.docker.db
    expose:
      - 5432
  nginx:
    build: ./docker/nginx
    volumes:
      - static_volume:/home/app/web/.staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - '1337:80'
    depends_on:
      - web
  cache:
    image: redis:7.0-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - cache:/data



volumes:
  postgres_data:
  static_volume:
  media_volume:
  cache:
